sonar.projectKey=tranduyloc895_retail-store-microservices
sonar.projectName=retail-store-microservices
sonar.organization=tranduyloc895
sonar.host.url=https://sonarcloud.io

sonar.sources=.
sonar.exclusions=**/*_test.go,vendor/**

sonar.tests=.
sonar.test.inclusions=**/*_test.go

# Coverage (sau khi viết test)
sonar.go.coverage.reportPaths=coverage.out